//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expansion_CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expansion_CSharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # UnrealEd OBJ exporter (_Internal)
        ///
        ///
        ///
        ///v 222.375885 78.474327 -14.926209
        ///
        ///v 202.665039 85.232674 -36.905838
        ///
        ///v 220.906891 92.057892 -14.683959
        ///
        ///v 205.502411 76.318207 -57.387135
        ///
        ///v 213.999023 71.486328 -34.734612
        ///
        ///v 192.838089 76.537781 -92.310745
        ///
        ///v 178.918594 37.881790 -18.354168
        ///
        ///v 204.283295 51.403183 -30.954538
        ///
        ///v 187.205597 57.305561 -31.549282
        ///
        ///v 172.028809 38.689312 -71.347443
        ///
        ///v 158.356949 22.990931 -8.677656
        ///
        ///v 176.719009 19.403290 -9.484483
        ///
        ///v 155.158676 14.942038 -47. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SM_Rock_Chunk {
            get {
                return ResourceManager.GetString("SM_Rock_Chunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T_Brick_Clay_Old_D {
            get {
                object obj = ResourceManager.GetObject("T_Brick_Clay_Old_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T_Brick_Clay_Old_N {
            get {
                object obj = ResourceManager.GetObject("T_Brick_Clay_Old_N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
